version: '3.8'
services:
  server:
    container_name: nodejs-bare-http
    volumes:
      - .:/app
      - /app/node_modules
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
